//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplicationlast.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback area_rectangleOperationCompleted;
        
        private System.Threading.SendOrPostCallback area_squareOperationCompleted;
        
        private System.Threading.SendOrPostCallback area_circleOperationCompleted;
        
        private System.Threading.SendOrPostCallback area_triangleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::WebApplicationlast.Properties.Settings.Default.WebApplicationlast_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event area_rectangleCompletedEventHandler area_rectangleCompleted;
        
        /// <remarks/>
        public event area_squareCompletedEventHandler area_squareCompleted;
        
        /// <remarks/>
        public event area_circleCompletedEventHandler area_circleCompleted;
        
        /// <remarks/>
        public event area_triangleCompletedEventHandler area_triangleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/area_rectangle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int area_rectangle(int l, int w) {
            object[] results = this.Invoke("area_rectangle", new object[] {
                        l,
                        w});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void area_rectangleAsync(int l, int w) {
            this.area_rectangleAsync(l, w, null);
        }
        
        /// <remarks/>
        public void area_rectangleAsync(int l, int w, object userState) {
            if ((this.area_rectangleOperationCompleted == null)) {
                this.area_rectangleOperationCompleted = new System.Threading.SendOrPostCallback(this.Onarea_rectangleOperationCompleted);
            }
            this.InvokeAsync("area_rectangle", new object[] {
                        l,
                        w}, this.area_rectangleOperationCompleted, userState);
        }
        
        private void Onarea_rectangleOperationCompleted(object arg) {
            if ((this.area_rectangleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.area_rectangleCompleted(this, new area_rectangleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/area_square", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int area_square(int s) {
            object[] results = this.Invoke("area_square", new object[] {
                        s});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void area_squareAsync(int s) {
            this.area_squareAsync(s, null);
        }
        
        /// <remarks/>
        public void area_squareAsync(int s, object userState) {
            if ((this.area_squareOperationCompleted == null)) {
                this.area_squareOperationCompleted = new System.Threading.SendOrPostCallback(this.Onarea_squareOperationCompleted);
            }
            this.InvokeAsync("area_square", new object[] {
                        s}, this.area_squareOperationCompleted, userState);
        }
        
        private void Onarea_squareOperationCompleted(object arg) {
            if ((this.area_squareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.area_squareCompleted(this, new area_squareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/area_circle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double area_circle(int r) {
            object[] results = this.Invoke("area_circle", new object[] {
                        r});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void area_circleAsync(int r) {
            this.area_circleAsync(r, null);
        }
        
        /// <remarks/>
        public void area_circleAsync(int r, object userState) {
            if ((this.area_circleOperationCompleted == null)) {
                this.area_circleOperationCompleted = new System.Threading.SendOrPostCallback(this.Onarea_circleOperationCompleted);
            }
            this.InvokeAsync("area_circle", new object[] {
                        r}, this.area_circleOperationCompleted, userState);
        }
        
        private void Onarea_circleOperationCompleted(object arg) {
            if ((this.area_circleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.area_circleCompleted(this, new area_circleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/area_triangle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double area_triangle(int b, int h) {
            object[] results = this.Invoke("area_triangle", new object[] {
                        b,
                        h});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void area_triangleAsync(int b, int h) {
            this.area_triangleAsync(b, h, null);
        }
        
        /// <remarks/>
        public void area_triangleAsync(int b, int h, object userState) {
            if ((this.area_triangleOperationCompleted == null)) {
                this.area_triangleOperationCompleted = new System.Threading.SendOrPostCallback(this.Onarea_triangleOperationCompleted);
            }
            this.InvokeAsync("area_triangle", new object[] {
                        b,
                        h}, this.area_triangleOperationCompleted, userState);
        }
        
        private void Onarea_triangleOperationCompleted(object arg) {
            if ((this.area_triangleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.area_triangleCompleted(this, new area_triangleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void area_rectangleCompletedEventHandler(object sender, area_rectangleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class area_rectangleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal area_rectangleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void area_squareCompletedEventHandler(object sender, area_squareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class area_squareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal area_squareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void area_circleCompletedEventHandler(object sender, area_circleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class area_circleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal area_circleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void area_triangleCompletedEventHandler(object sender, area_triangleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class area_triangleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal area_triangleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591